name: kushi3
description: A sample command-line application with basic argument parsing.
publish_to: 'none'
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3




dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

